### ISSUE TITLE
Error Update Cards

### ISSUE THREAD

**Issue by Kamanreza** [vanhbakaa/Cexio-Tap-bot#21]
tapper.py", line 565, in run
    check = await self.buyUpgrade(http_client, authToken, sorted_potential_card[card])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Bots\Telegram Bots\Cexio-Bot\bot\core\tapper.py", line 472, in buyUpgrade
    self.coin_balance -= Buydata['cost']
TypeError: unsupported operand type(s) for -=: 'str' and 'int'

**Comment by vanhbakaa** [comment]
Fixed

**Comment by Kamanreza** [comment]
error changed to 
Traceback (most recent call last):
  File "G:\Bots\Telegram Bots\Cxio-new\bot\core\tapper.py", line 565, in run
    check = await self.buyUpgrade(http_client, authToken, sorted_potential_card[card])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Bots\Telegram Bots\Cxio-new\bot\core\tapper.py", line 472, in buyUpgrade
    self.coin_balance -= int(Buydata['cost'])
TypeError: unsupported operand type(s) for -=: 'str' and 'int'
