### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MelikUltra** [vanhbakaa/Cexio-Tap-bot#29]
Traceback (most recent call last):
  File "C:\Users\ULTRA\Desktop\tele bot\Cexio-Vanh\Melik\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\ULTRA\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ULTRA\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ULTRA\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\ULTRA\Desktop\tele bot\Cexio-Vanh\Melik\main.py", line 8, in main
    await process()
  File "C:\Users\ULTRA\Desktop\tele bot\Cexio-Vanh\Melik\bot\utils\launcher.py", line 105, in process
    await run_tasks(tg_clients=tg_clients)
  File "C:\Users\ULTRA\Desktop\tele bot\Cexio-Vanh\Melik\bot\utils\launcher.py", line 111, in run_tasks
    tasks = [
            ^
  File "C:\Users\ULTRA\Desktop\tele bot\Cexio-Vanh\Melik\bot\utils\launcher.py", line 113, in <listcomp>
    run_tapper(
TypeError: run_tapper() missing 1 required positional argument: 'app_version'

**Comment by vanhbakaa** [comment]
You need to update the project...

**Comment by vanhbakaa** [comment]
i think you forgot to update tapper.py

**Comment by MelikUltra** [comment]
i luv your codes, and your activities for updating very quickly , appreciated
