### ISSUE TITLE
Auto Upgrade

### ISSUE THREAD

**Issue by PTPL-LKO** [vanhbakaa/Cexio-Tap-bot#31]
Hi,

When will you introduce auto-upgrade mining, power and business levels?

**Comment by vanhbakaa** [comment]
What do you mean bro

**Comment by PTPL-LKO** [comment]
I mean, every time I open the app, I have to upgrade levels myself.

**Comment by vanhbakaa** [comment]
> I mean, every time I open the app, I have to upgrade levels myself.

show me your setting in config file

**Comment by PTPL-LKO** [comment]
Sure,

`
REF_LINK='https://t.me/cexio_tap_bot?start=1724837623952742'

AUTO_TAP=True
RANDOM_TAPS_COUNT=[5, 50]
SLEEP_BETWEEN_TAPS=[25, 35]
SLEEP_BY_MIN_ENERGY=250
AUTO_CONVERT=True
MINIMUM_TO_CONVERT=0.01
AUTO_BUY_UPGRADE=True
WAIT_FOR_MOST_PROFITABLE_CARD= True
AUTO_TASK=True
AUTO_CLAIM_SQUAD_BONUS=True

USE_PROXY_FROM_FILE=False`

**Comment by vanhbakaa** [comment]
WAIT_FOR_MOST_PROFITABLE_CARD=
Set to false

**Comment by PTPL-LKO** [comment]
Thanks, But got in problem:

```
2024-09-19 17:16:29 | INFO     | 93 - Detected 8 sessions | 0 proxies
2024-09-19 17:16:29 | INFO     | 60 - Trying format: /static/js/main.59e513c0.js
2024-09-19 17:16:29 | INFO     | 52 - Version updated to 0.12.0 and saved to x-appl-version.txt


 __   ___        __      __   __  ___
/  ` |__  \_/ | /  \    |__) /  \  |
\__, |___ / \ | \__/    |__) \__/  |

            BY VANHBAKA

Select an action:

    1. Run clicker
    2. Create session

> 1
2024-09-19 17:16:32 | INFO     | 607 - 1_Jio | Update auth token...
2024-09-19 17:16:32 | INFO     | 72 - Getting data for 1_Jio
2024-09-19 17:16:32 | INFO     | 607 - 2_JioZ | Update auth token...
2024-09-19 17:16:32 | INFO     | 72 - Getting data for 2_JioZ
2024-09-19 17:16:32 | INFO     | 607 - 3_AirZ | Update auth token...
2024-09-19 17:16:32 | INFO     | 72 - Getting data for 3_AirZ
2024-09-19 17:16:33 | INFO     | 607 - 5_hanz | Update auth token...
2024-09-19 17:16:33 | INFO     | 72 - Getting data for 5_hanz
2024-09-19 17:16:33 | INFO     | 607 - 6_Me | Update auth token...
2024-09-19 17:16:33 | INFO     | 72 - Getting data for 6_Me
2024-09-19 17:16:33 | INFO     | 607 - Shri2 | Update auth token...
2024-09-19 17:16:33 | INFO     | 72 - Getting data for Shri2
2024-09-19 17:16:33 | INFO     | 607 - ShriBro | Update auth token...
2024-09-19 17:16:33 | INFO     | 72 - Getting data for ShriBro
2024-09-19 17:16:33 | INFO     | 607 - shri | Update auth token...
2024-09-19 17:16:33 | INFO     | 72 - Getting data for shri
2024-09-19 17:16:44 | INFO     | 617 - Session Shri Kant","language_code":"en","allows_write_to_pm":true}&auth_date=1726746394&hash=95a613e7e7fcb3ea4a8df90dffa3be7b84c02e60daa199eca857651e8942e31f logged in.
2024-09-19 17:16:44 | INFO     | 617 - Session Shri Kant","language_code":"en","allows_write_to_pm":true}&auth_date=1726746394&hash=a48e7c520a77ae8af4fb901e9e24df8e358a5f9718634817d6071e2dab4f119e logged in.
2024-09-19 17:16:44 | ERROR    | 199 - Error while getting user data. Response 444. Try again after 30s
2024-09-19 17:16:44 | ERROR    | 199 - Error while getting user data. Response 444. Try again after 30s
2024-09-19 17:16:45 | INFO     | 617 - Session Huzaifa Ansari logged in.
2024-09-19 17:16:45 | INFO     | 617 - Session Krishna Kumar","language_code":"en","allows_write_to_pm":true}&auth_date=1726746394&hash=231b587cfaef0fdf8149fd4b1f4ffa82bdcba01bb19535847718d821f2fc692b logged in.
2024-09-19 17:16:45 | INFO     | 617 - Session Whistle Bowler logged in.
2024-09-19 17:16:45 | ERROR    | 199 - Error while getting user data. Response 444. Try again after 30s
2024-09-19 17:16:45 | INFO     | 617 - Session Z Star logged in.
2024-09-19 17:16:45 | ERROR    | 199 - Error while getting user data. Response 444. Try again after 30s
2024-09-19 17:16:45 | ERROR    | 199 - Error while getting user data. Response 444. Try again after 30s
2024-09-19 17:16:46 | ERROR    | 199 - Error while getting user data. Response 444. Try again after 30s
2024-09-19 17:16:47 | INFO     | 617 - Session Marsh Mellow logged in.
2024-09-19 17:16:47 | ERROR    | 199 - Error while getting user data. Response 444. Try again after 30s
2024-09-19 17:16:49 | INFO     | 617 - Session Safiuddin Ansari logged in.
2024-09-19 17:16:49 | ERROR    | 199 - Error while getting user data. Response 444. Try again after 30s
2024-09-19 17:17:15 | ERROR    | 424 - shri | Error code 444 While trying to get data
2024-09-19 17:17:15 | ERROR    | 424 - Shri2 | Error code 444 While trying to get data
2024-09-19 17:17:15 | WARNING  | 223 - shri | Failed to get special tasks data. Response code: 444
2024-09-19 17:17:15 | INFO     | 640 - shri | No special tasks now!
2024-09-19 17:17:15 | WARNING  | 223 - Shri2 | Failed to get special tasks data. Response code: 444
2024-09-19 17:17:15 | INFO     | 640 - Shri2 | No special tasks now!
2024-09-19 17:17:15 | ERROR    | 445 - shri | Error code 444 While trying to get completed task
Traceback (most recent call last):
  File "D:\Work\cexio\Cexio-Tap-bot\bot\core\tapper.py", line 642, in run
    for task in self.task:
TypeError: 'NoneType' object is not iterable
2024-09-19 17:17:15 | ERROR    | 720 - shri | Unknown error: 'NoneType' object is not iterable
2024-09-19 17:17:15 | ERROR    | 445 - Shri2 | Error code 444 While trying to get completed task
Traceback (most recent call last):
  File "D:\Work\cexio\Cexio-Tap-bot\bot\core\tapper.py", line 642, in run
    for task in self.task:
TypeError: 'NoneType' object is not iterable
2024-09-19 17:17:15 | ERROR    | 720 - Shri2 | Unknown error: 'NoneType' object is not iterable
2024-09-19 17:17:15 | ERROR    | 424 - 5_hanz | Error code 444 While trying to get data
2024-09-19 17:17:16 | ERROR    | 424 - ShriBro | Error code 444 While trying to get data
2024-09-19 17:17:16 | ERROR    | 424 - 1_Jio | Error code 444 While trying to get data
2024-09-19 17:17:16 | WARNING  | 223 - 5_hanz | Failed to get special tasks data. Response code: 444
2024-09-19 17:17:16 | INFO     | 640 - 5_hanz | No special tasks now!
2024-09-19 17:17:16 | ERROR    | 424 - 3_AirZ | Error code 444 While trying to get data
2024-09-19 17:17:16 | WARNING  | 223 - ShriBro | Failed to get special tasks data. Response code: 444
2024-09-19 17:17:16 | INFO     | 640 - ShriBro | No special tasks now!
2024-09-19 17:17:16 | WARNING  | 223 - 1_Jio | Failed to get special tasks data. Response code: 444
2024-09-19 17:17:16 | INFO     | 640 - 1_Jio | No special tasks now!
2024-09-19 17:17:16 | ERROR    | 445 - 5_hanz | Error code 444 While trying to get completed task
Traceback (most recent call last):
  File "D:\Work\cexio\Cexio-Tap-bot\bot\core\tapper.py", line 642, in run
    for task in self.task:
TypeError: 'NoneType' object is not iterable
2024-09-19 17:17:16 | ERROR    | 720 - 5_hanz | Unknown error: 'NoneType' object is not iterable
2024-09-19 17:17:16 | WARNING  | 223 - 3_AirZ | Failed to get special tasks data. Response code: 444
2024-09-19 17:17:16 | INFO     | 640 - 3_AirZ | No special tasks now!
2024-09-19 17:17:16 | ERROR    | 445 - 1_Jio | Error code 444 While trying to get completed task
Traceback (most recent call last):
  File "D:\Work\cexio\Cexio-Tap-bot\bot\core\tapper.py", line 642, in run
    for task in self.task:
TypeError: 'NoneType' object is not iterable
2024-09-19 17:17:16 | ERROR    | 720 - 1_Jio | Unknown error: 'NoneType' object is not iterable
2024-09-19 17:17:16 | ERROR    | 445 - ShriBro | Error code 444 While trying to get completed task
Traceback (most recent call last):
  File "D:\Work\cexio\Cexio-Tap-bot\bot\core\tapper.py", line 642, in run
    for task in self.task:
TypeError: 'NoneType' object is not iterable
2024-09-19 17:17:16 | ERROR    | 720 - ShriBro | Unknown error: 'NoneType' object is not iterable
2024-09-19 17:17:16 | ERROR    | 445 - 3_AirZ | Error code 444 While trying to get completed task
Traceback (most recent call last):
  File "D:\Work\cexio\Cexio-Tap-bot\bot\core\tapper.py", line 642, in run
    for task in self.task:
TypeError: 'NoneType' object is not iterable
2024-09-19 17:17:16 | ERROR    | 720 - 3_AirZ | Unknown error: 'NoneType' object is not iterable
2024-09-19 17:17:18 | ERROR    | 424 - 2_JioZ | Error code 444 While trying to get data
2024-09-19 17:17:18 | WARNING  | 223 - 2_JioZ | Failed to get special tasks data. Response code: 444
2024-09-19 17:17:18 | INFO     | 640 - 2_JioZ | No special tasks now!
2024-09-19 17:17:18 | ERROR    | 445 - 2_JioZ | Error code 444 While trying to get completed task
Traceback (most recent call last):
  File "D:\Work\cexio\Cexio-Tap-bot\bot\core\tapper.py", line 642, in run
    for task in self.task:
TypeError: 'NoneType' object is not iterable
2024-09-19 17:17:18 | ERROR    | 720 - 2_JioZ | Unknown error: 'NoneType' object is not iterable
2024-09-19 17:17:20 | ERROR    | 424 - 6_Me | Error code 444 While trying to get data
2024-09-19 17:17:20 | WARNING  | 223 - 6_Me | Failed to get special tasks data. Response code: 444
2024-09-19 17:17:20 | INFO     | 640 - 6_Me | No special tasks now!
2024-09-19 17:17:20 | ERROR    | 445 - 6_Me | Error code 444 While trying to get completed task
Traceback (most recent call last):
  File "D:\Work\cexio\Cexio-Tap-bot\bot\core\tapper.py", line 642, in run
    for task in self.task:
TypeError: 'NoneType' object is not iterable
2024-09-19 17:17:20 | ERROR    | 720 - 6_Me | Unknown error: 'NoneType' object is not iterable
2024-09-19 17:18:18 | INFO     | 617 - Session Whistle Bowler logged in.
2024-09-19 17:18:18 | ERROR    | 199 - Error while getting user data. Response 444. Try again after 30s
2024-09-19 17:18:23 | INFO     | 617 - Session Shri Kant","language_code":"en","allows_write_to_pm":true}&auth_date=1726746394&hash=95a613e7e7fcb3ea4a8df90dffa3be7b84c02e60daa199eca857651e8942e31f logged in.
```

**Comment by PTPL-LKO** [comment]
Thanks for fixing issue, but I don't want to upgrade special cards with 0 power.

**Comment by vanhbakaa** [comment]
> Thanks for fixing issue, but I don't want to upgrade special cards with 0 power.

It wont upgrade that
