### ISSUE TITLE
Getting Error , Fix please 

### ISSUE THREAD

**Issue by bootfast** [vanhbakaa/Cexio-Tap-bot#48]
ERROR    | 199 - Error while getting user data. Response 401. Try again after 30s

**Comment by bootfast** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Cexio-Tap-bot/bot/core/tapper.py", line 644, in run

**Comment by 1573712107** [comment]
me too

**Comment by 1573712107** [comment]
2024-10-17 22:51:36 | ERROR    | 720 - xx | Unknown error: 'NoneType' object is not iterable
2024-10-17 22:51:36 | ERROR    | 424 - xx| Error code 401 While trying to get data
Traceback (most recent call last):
  File "D:\TGbot\Cexio-Tap-bot\bot\core\tapper.py", line 664, in run
    await self.find_potential()
  File "D:\TGbot\Cexio-Tap-bot\bot\core\tapper.py", line 515, in find_potential
    for category in self.card:
TypeError: 'NoneType' object is not iterable

**Comment by vanhbakaa** [comment]
Update new version and wait
