### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by supmyhava** [vanhbakaa/Cexio-Tap-bot#49]
2024-10-17 20:10:10 | INFO     | 619 - Session bb logged in.
2024-10-17 20:10:11 | ERROR    | 205 - Error while getting user data. Response 401. Try again after 30s
2024-10-17 20:10:14 | INFO     | 619 - Session aa logged in.
2024-10-17 20:10:14 | ERROR    | 205 - Error while getting user data. Response 401. Try again after 30s
2024-10-17 20:10:20 | INFO     | 619 - Session cc logged in.
2024-10-17 20:10:20 | ERROR    | 205 - Error while getting user data. Response 401. Try again after 30s
2024-10-17 20:10:41 | ERROR    | 430 - cc | Error code 401 While trying to get data
2024-10-17 20:10:41 | WARNING  | 229 - cc | Failed to get special tasks data. Response code: 401
2024-10-17 20:10:41 | INFO     | 642 - cc | No special tasks now!
2024-10-17 20:10:41 | ERROR    | 451 - cc | Error code 401 While trying to get completed task
Traceback (most recent call last):
  File "/root/Cexio-Tap-bot/bot/core/tapper.py", line 644, in run
    for task in self.task:
TypeError: 'NoneType' object is not iterable
2024-10-17 20:10:41 | ERROR    | 720 - cc | Unknown error: 'NoneType' object is not iterable
2024-10-17 20:10:45 | ERROR    | 430 - aa  | Error code 401 While trying to get data
2024-10-17 20:10:45 | WARNING  | 229 - aa | Failed to get special tasks data. Response code: 401
2024-10-17 20:10:45 | INFO     | 642 - aa | No special tasks now!
2024-10-17 20:10:45 | ERROR    | 451 - aa | Error code 401 While trying to get completed task
Traceback (most recent call last):
  File "/root/Cexio-Tap-bot/bot/core/tapper.py", line 644, in run
    for task in self.task:
TypeError: 'NoneType' object is not iterable
2024-10-17 20:10:45 | ERROR    | 720 - aa | Unknown error: 'NoneType' object is not iterable

**Comment by iskizreal** [comment]
the same

**Comment by Niyaz-Mahmud** [comment]
Same here too

**Comment by vanhbakaa** [comment]
https://t.me/airdrop_tool_vanh/99
